<?php

namespace KittyBot\Services;

final class ComposeOverrideWriter
{
    public function __construct(private string $path = '/docker/services-compose')
    {
    }

    /** @param array<string,bool> $states */
    public function write(array $states): void
    {
        $disabled = [];
        foreach (ServiceCatalog::OPTIONAL as $service) {
            if (($states[$service] ?? true) === false) {
                $disabled[] = $service;
            }
        }

        $dir = dirname($this->path);
        if (!is_dir($dir)) {
            mkdir($dir, 0750, true);
        }

        if (!$disabled) {
            file_put_contents($this->path, '');
            return;
        }

        $yaml = [
            '# Generated by kittybot. Do not edit by hand.',
            'services:',
            '  up:',
            '    depends_on: !override',
            '      ng:',
            '        condition: service_healthy',
            '  ng:',
            '    depends_on: !override',
            '      php:',
            '        condition: service_healthy',
            '  service:',
            '    depends_on: !override',
            '      - up',
            '      - ng',
            '      - php',
        ];

        foreach ($disabled as $service) {
            $yaml[] = "  $service:";
            $yaml[] = '    profiles:';
            $yaml[] = '      - disabled';
        }

        $content = implode("\n", $yaml) . "\n";
        file_put_contents($this->path, $content);
    }
}
